
import { BadRequestException } from '../common/helper/error.helper.js';
import { responseSuccess, responseError, handleSuccess } from '../common/helper/response.helper.js';
import { authService } from '../service/auth.service.js';
const checkPermission = {
    protect: async(req, res, next)=> {
        try{
           
        }catch(error){
            next(error)
        }
    },
    protect: async(req, res, next)=> {
        try{
           
        }catch(error){
            next(error)
        }
    },
    protect: async(req, res, next)=> {
        try{
           
        }catch(error){
            next(error)
        }
    },
    protect: async(req, res, next)=> {
        try{
           
        }catch(error){
            next(error)
        }
    },
}
export default checkPermission